# Generated by Django 4.0.3 on 2022-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocopy',
            name='item_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
